export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
    GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
    GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
    
  }
  
  export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
  
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",
};

export const userconstants={
    USER_REGISTER_REQUEST:'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS:'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE:'USER_REGISTER_FAILURE'
}

export const productConstants = {
  GET_PRODUCTS_BY_SLUG: "GET_PRODUCTS_BY_SLUG",  
  GET_PRODUCT_DETAILS_BY_ID_REQUEST: "GET_PRODUCT_DETAILS_BY_ID_REQUEST",
  GET_PRODUCT_DETAILS_BY_ID_SUCCESS: "GET_PRODUCT_DETAILS_BY_ID_SUCCESS",
  GET_PRODUCT_DETAILS_BY_ID_FAILURE: "GET_PRODUCT_DETAILS_BY_ID_FAILURE"

}


export const contractConstants= {
  GET_ALL_CONTRACTS_REQUEST :"GET_ALL_CONTRACTS_REQUEST",
  GET_ALL_CONTRACTS_SUCCESS :"GET_ALL_CONTRACTS_SUCCESS",
  GET_ALL_CONTRACTS_FAILURE :"GET_ALL_CONTRACTS_FAILURE",
  ADD_CONTRACTS_REQUEST: "ADD_CONTRACTS_REQUEST",
  ADD_CONTRACTS_SUCCESS: "ADD_CONTRACTS_SUCCESS",
  ADD_CONTRACTS_FAILURE: "ADD_CONTRACTS_FAILURE",
  
  }

  
export const reqConstants= {
  ADD_REQ_REQUEST: "ADD_REQ_REQUEST",
  ADD_REQ_SUCCESS: "ADD_REQ_SUCCESS",
  ADD_REQ_FAILURE: "ADD_REQ_FAILURE",
  GET_ALL_REQ_REQUEST :"GET_ALL_REQ_REQUEST",
  GET_ALL_REQ_SUCCESS :"GET_ALL_REQ_SUCCESS",
  GET_ALL_REQ_FAILURE :"GET_ALL_REQ_FAILURE",
  
  }