export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
  
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",
};

export const userconstants={
    USER_REGISTER_REQUEST:'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS:'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE:'USER_REGISTER_FAILURE'
}

export const productConstants={
    GET_ALL_PRODUCTS_REQUEST:"GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS:"GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILURE:"GET_ALL_PRODUCTS_FAILURE",
    ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
}

export const categoryConstants={
  GET_ALL_CATEGORIES_REQUEST:"GET_ALL_CATEGORIES_REQUEST",
  GET_ALL_CATEGORIES_SUCCESS:"GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE:"GET_ALL_CATEGORIES_FAILURE",
  ADD_NEW_CATEGORY_REQUEST:"ADD_NEW_CATEGORY_REQUEST",
  ADD_NEW_CATEGORY_SUCCESS:"ADD_NEW_CATEGORY_SUCCESS",
  ADD_NEW_CATEGORY_FAILURE:"ADD_NEW_CATEGORY_FAILURE",
}

export const contractConstants={
  GET_ALL_CONTRACTS_REQUEST :"GET_ALL_CONTRACTS_REQUEST",
  GET_ALL_CONTRACTS_SUCCESS :"GET_ALL_CONTRACTS_SUCCESS",
  GET_ALL_CONTRACTS_FAILURE :"GET_ALL_CONTRACTS_FAILURE",
  ADD_CONTRACTS_REQUEST: "ADD_CONTRACTS_REQUEST",
  ADD_CONTRACTS_SUCCESS: "ADD_CONTRACTS_SUCCESS",
  ADD_CONTRACTS_FAILURE: "ADD_CONTRACTS_FAILURE",
  
  }

export const reqPostConstants ={
  GET_ALL_REQ_REQUEST:"GET_ALL_REQ_REQUEST",
  GET_ALL_REQ_SUCCESS:"GET_ALL_REQ_SUCCESS",
  GET_ALL_REQ_FAILURE:"GET_ALL_REQ_FAILURE"
}